# Generated by Django 4.0.4 on 2022-05-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('mdesc', models.CharField(max_length=50)),
                ('mprice', models.FloatField()),
            ],
        ),
    ]
