# Generated by Django 4.0.4 on 2022-05-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='mdesc',
            field=models.CharField(max_length=500),
        ),
    ]
