# Generated by Django 4.0.4 on 2022-05-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_testimonials_trainers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='texperience',
            field=models.CharField(max_length=200),
        ),
    ]
